server:
  port: 8090

mybatis:
  mapper-locations: classpath:mapping/*.xml
spring:
  datasource:
    name: criticism
    url: jdbc:mysql://111.230.138.67:3306/delivery
    username: root
    password: fehead123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.alibaba.druid.proxy.DruidDriver
  application:
    name: anonymous-critism
ribbon:
  ReadTimeout: 6000000
  ConnectTimeout: 6000000
feign:
  client:
    config:
      defualt:
        connectTimeout: 20000
        readTimeout: 20000


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka