server:
  port: 8090

mybatis:
  mapper-locations: classpath:mapping/*.xml
spring:
  datasource:
    name: criticism
    url: 
    username: 
    password: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.alibaba.druid.proxy.DruidDriver
  application:
    name: anonymous-critism
ribbon:
  ReadTimeout: 6000000
  ConnectTimeout: 6000000
feign:
  client:
    config:
      defualt:
        connectTimeout: 20000
        readTimeout: 20000


eureka:
  client:
    service-url:
      defaultZone: 
